version: '2'
services:
  nginx:
    links:
    - bablot_web_node:node
    - landing:landing
    ports:
    - "80:80"
    - "443:443"
  bablot_web_node:
    ports:
    - "8000:8000"
  landing:
    ports:
    - "8001:8001"
