version: '2'
services:
  nginx:
    build: ./nginx
  bablot_web_node:
    build: ./
    command: npm run dev
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    ports:
    - "8000:8000"
  landing:
    build: ./landing
    command: npm run dev
    volumes:
    - /usr/src/app/node_modules
    - ./landing:/usr/src/app
