version: '2'
services:
  nginx:
    build: ./nginx
  bablot_web_node:
    build: ./
    command: npm run dev
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    environment:
      BABLOT_API_URL: 'https://dev.api.bablot.co:9000'
  landing:
    environment:
      NODE_ENV: 'development'
      BABLOT_API_URL: 'https://dev.api.bablot.co:9000'
    build: ./landing
    command: npm run dev
    volumes:
    - /usr/src/app/node_modules
    - ./landing:/usr/src/app
