version: '2'
services:
  nginx:
    build: ./nginx
  portal:
    build: ./portal
    command: npm run dev
    volumes:
    - ./portal:/usr/src/app
    - /usr/src/app/node_modules
    environment:
      BABLOT_API_URL: 'https://162.243.218.96:9000'
  landing:
    environment:
      NODE_ENV: 'development'
      BABLOT_API_URL: 'https://162.243.218.96:9000'
    build: ./landing
    command: npm run dev
    volumes:
    - ./landing:/usr/src/app
    - /usr/src/app/node_modules
