version: '2'
services:
  nginx:
    links:
    - portal:portal
    - landing:landing
    ports:
    - "80:80"
    - "443:443"
  portal:
    ports:
    - "8000:8000"
  landing:
    ports:
    - "8001:8001"
