version: '2'
services:
  nginx:
    image: bablot/web-nginx
  bablot_web_node:
    image: bablot/web
    command: npm start
    environment:
      BABLOT_API_URL: 'https://api.bablot.co:9000'
  landing:
    image: bablot/landing
    command: npm start
