version: '2'
services:
  nginx:
    image: bablot/web-nginx
  portal:
    image: bablot/portal
    command: npm start
    environment:
      BABLOT_API_URL: 'https://162.243.218.96:9000'
  landing:
    environment:
      NODE_ENV: 'production'
      BABLOT_API_URL: 'https://162.243.218.96:9000'
    image: bablot/landing
    command: npm start
